name: CI

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  eslint:
    name: Lint code base
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn
      - name: Run ESlint
        run: yarn lint